[package]
name = "rtest"
description = "Rust Unit Test Framework"
version = "1.0.0"
edition = "2021"
license = "MIT"

[dependencies]
chrono = "0.4.19"
console = "0.12.0"
convert_case = "0.4.0"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"